# Generated by Django 6.0.6 on 2026-06-04 07:24

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(blank=True, editable=False, max_length=30, unique=True, verbose_name='Ticket Number')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('department', models.CharField(choices=[('Purchase', 'Purchase'), ('Inventory', 'Inventory'), ('Production', 'Production'), ('PPC', 'PPC'), ('Accounts', 'Accounts'), ('HR', 'HR'), ('IT', 'IT'), ('Sales', 'Sales'), ('Other', 'Other')], max_length=50, verbose_name='Department')),
                ('issue_type', models.CharField(choices=[('ERP Issue', 'ERP Issue'), ('BOM Issue', 'BOM Issue'), ('Purchase Issue', 'Purchase Issue'), ('Inventory Issue', 'Inventory Issue'), ('Production Issue', 'Production Issue'), ('Network Issue', 'Network Issue'), ('Hardware Issue', 'Hardware Issue'), ('Software Issue', 'Software Issue'), ('Other', 'Other')], max_length=60, verbose_name='Issue Type')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20, verbose_name='Priority')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('description', models.TextField(verbose_name='Detailed Description')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=tickets.models.ticket_attachment_path, verbose_name='Attachment')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
