# Generated by Django 6.0.1 on 2026-06-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterNameOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Filter Name Option')),
            ],
            options={
                'verbose_name': 'Filter Name Option',
                'verbose_name_plural': 'Filter Name Options',
                'ordering': ['name'],
            },
        ),
    ]
