# Generated by Django 6.0.1 on 2026-06-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_filternameoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Department Name')),
            ],
            options={
                'verbose_name': 'Department Option',
                'verbose_name_plural': 'Department Options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IssueTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Issue Type Name')),
            ],
            options={
                'verbose_name': 'Issue Type Option',
                'verbose_name_plural': 'Issue Type Options',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(max_length=50, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue_type',
            field=models.CharField(max_length=60, verbose_name='Issue Type'),
        ),
    ]
