# Generated by Django 6.0.1 on 2026-06-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_departmentoption_issuetypeoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='email',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Number'),
        ),
    ]
