# Generated by Django 6.0.1 on 2026-06-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticket_email_alter_ticket_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20, verbose_name='Status'),
        ),
    ]
