# Generated by Django 6.0.1 on 2026-06-10 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='subject',
        ),
    ]
