# Generated by Django 6.0.1 on 2026-06-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticket_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue_type',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Issue Type'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], db_index=True, default='Medium', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], db_index=True, default='Open', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_no',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=30, unique=True, verbose_name='Ticket Number'),
        ),
    ]
